### ISSUE TITLE
404 ошибки на компонентах при установке на LAMP.

### ISSUE THREAD

**Issue by grkwebdev** [instantsoft/icms1#5]
Сервер на Ubuntu 14.04 
Сверху, из стандартного tasksel'a поднят LAMP.
Обнаружилось после установке, что ЧПУ отказывается работать. 
Если быть точнее - по реальным ссылкам все работает нормально, т.е. /admin/, /index.php

А вот при переходе к компоненту, например, /forum, отдается 404 ошибка. И так везде. После выхода из админки на отключенном сайте стало невозможно залогиниться снова, т.к. с /admin при авторизации перекидывает на /login, а там 404. 

Проверял и mod_rewrite, и mods_enabled, все без толку.

**Comment by fuzegit** [comment]
Для вопросов у нас есть форум. А проблема ваша решается установкой mod_rewrite и директивой AllowOverride All в конфигурации apache. CMS тут не при чем.
