### ISSUE TITLE
Формирование корректного урл в виджетах типов контента по умолчанию

### ISSUE THREAD

**Issue by vlad7090** [instantsoft/icms1#9]
Версия 2.12. Почему в виджетах формируется с урл типа контента, если даже этот тип задание по умолчанию. Для сео лучше прямой путь.

**Comment by fuzegit** [comment]
Ошиблись веткой
https://github.com/instantsoft/icms2/issues

Но всё равно отвечу. На дефолтной установке и дефолтном шаблоне проблемы не наблюдаю.
